docker:
  service: docker
  package: docker-ce

  package_dependencies:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common

  container_uid: 1001
  container_gid: 1001
  path:
    windows:
    osx:
    linux: /etc/docker

  release:
    reference_doc: https://docs.docker.com/install/linux/docker-ce/ubuntu/
